### ISSUE TITLE
Ошибка при изменении данных о товара в Админке

### ISSUE THREAD

**Issue by OLYACHER23** [vitaliy-zinchenko/astro#3]
Заходим в Админку, нажимаем Products/Edit и изменяем Description на текст с запятыми и точками. Нажимаем сохранить и видим ошибку (в SQL) 
Если меняем просто на слово (пп) - ошибки нет.
![image](https://cloud.githubusercontent.com/assets/16743413/12377435/facb47a4-bd26-11e5-93e7-179487640d65.png)

**Comment by vitaliy-zinchenko** [comment]
не могу воспроизвести
