### ISSUE TITLE
Ошибка при создании нового товара

### ISSUE THREAD

**Issue by OLYACHER23** [vitaliy-zinchenko/astro#5]
Не выбрала поле Merchant (его плохо видно сейчас) и возникла вот такая ошибка. 
Исправить! 
Если администратор не выбрал случайно Merchant, или не заполнил то или иное поле - должна появлятся подсказка, а не Error.
![image](https://cloud.githubusercontent.com/assets/16743413/12377457/e21a3ee4-bd27-11e5-990a-4bf3242e7559.png)

**Comment by vitaliy-zinchenko** [comment]
была добавлена валидация на все формы админки. необходимо протестировать валидацию.
