### ISSUE TITLE
На продажнике кнопка Оплатить уехала влево

### ISSUE THREAD

**Issue by OLYACHER23** [vitaliy-zinchenko/astro#8]
1. Заходим на страницу выбора и оплаты услуг.
2.Нажимаем CHOOSE
3. Переходим и видим кнопку Оплатить слева на странице
![image](https://cloud.githubusercontent.com/assets/16743413/12377522/b62ac8ba-bd29-11e5-8efc-fbc2031a48d2.png)

**Comment by vitaliy-zinchenko** [comment]
кнопку "Оплатить нужно удалить"
