### ISSUE TITLE
Меняем названия

### ISSUE THREAD

**Issue by OLYACHER23** [vitaliy-zinchenko/astro#9]
1. Products на Астрологические услуги
![image](https://cloud.githubusercontent.com/assets/16743413/12377537/17adbf20-bd2a-11e5-82a9-6cc56bfd8280.png)
2. CHOOSE на Оплатить
![image](https://cloud.githubusercontent.com/assets/16743413/12377546/3a05223e-bd2a-11e5-8760-be173eee5197.png)
3. Форму Оплаты
You have to choosen - Вы выбрали услугу

User info - Информация о Клиенте
Please fill your name and contact data - Пожалуйста, введите ваше имя и контактные данные.
Имя
Фамилия
Моб.телефон
E-mail

![image](https://cloud.githubusercontent.com/assets/16743413/12377550/5c58f568-bd2a-11e5-850a-aede3babb28c.png)

**Comment by vitaliy-zinchenko** [comment]
Изменить название в табке браузера 
Изменить иконку в табке браузера
